# Generated by Django 5.2.4 on 2025-07-30 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("messaging", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="message",
            old_name="sent_at",
            new_name="timestamp",
        ),
    ]
