version: '3.8'

services:
  web:
    build: .
    container_name: messaging_app
    command: ./entrypoint.sh python3 manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - type: bind
        source: .
        target: /app
    environment:
      MYSQL_DB: messaging_db
      MYSQL_USER: messaging_user
      MYSQL_PASSWORD: toor
      MYSQL_ROOT_PASSWORD: toor
      APP_ENV: development
      APP_DEBUG: "true"
      DJANGO_SUPERUSER_FIRST_NAME: Admin
      DJANGO_SUPERUSER_LAST_NAME: User
      DJANGO_SUPERUSER_USERNAME: admin
      DJANGO_SUPERUSER_EMAIL: admin@example.com
      DJANGO_SUPERUSER_PASSWORD: admin123
    depends_on:
      - db
    networks:
      - backend
      - frontend

  db:
    image: mysql:8.0
    container_name: messaging_db
    restart: unless-stopped
    environment:
      MYSQL_DB: messaging_db
      MYSQL_USER: messaging_user
      MYSQL_PASSWORD: toor
      MYSQL_ROOT_PASSWORD: toor
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - backend

volumes:
  db_data:

networks:
  backend:
  frontend:
