FROM jenkins/jenkins:lts

USER root

# Install Python, pip, venv, Docker CLI, and git
RUN apt-get update && \
    apt-get install -y python3 python3-pip python3-venv docker.io git && \
    apt-get clean

# Install docker-compose
RUN curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" \
    -o /usr/local/bin/docker-compose \
    && chmod +x /usr/local/bin/docker-compose

# Add Jenkins user to Docker group
RUN usermod -aG docker jenkins

# USER jenkins

# Let the base image handle startup correctly
# ENTRYPOINT ["/usr/bin/tini", "--", "/usr/local/bin/jenkins.sh"]
