FROM jenkins/jenkins:lts

USER root

# Install Python, pip, venv, Docker CLI, and git
RUN apt-get update && \
    apt-get install -y python3 python3-pip python3-venv docker.io git && \
    apt-get clean

# Add Jenkins user to Docker group
RUN usermod -aG docker jenkins

USER jenkins

# Let the base image handle startup correctly
# ENTRYPOINT ["/usr/bin/tini", "--", "/usr/local/bin/jenkins.sh"]
