# version: '3.8'

services:
  web:
    build: .
    container_name: messaging_app
    command: ./entrypoint.sh python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - type: bind
        source: .
        target: /app
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - backend 
      - frontend
  db:
    image: mysql:8.0
    container_name: messaging_db
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - backend
volumes:
  db_data:  
networks:
  backend:
  frontend: