pipeline {
    agent any

    environment {
        MYSQL_DB = credentials('mysql_db')
        MYSQL_USER = credentials('mysql_user')
        MYSQL_PASSWORD = credentials('mysql_password')
    }

    stages {
        stage('Checkout Code') {
            steps {
                git branch: 'master',
                    url: 'https://github.com/ylb43u/alx-backend-python.git'
            }
        }

        stage('Start Services') {
            steps {
                sh '''
                    cd messaging_app
                    docker-compose up -d --build
                '''
            }
        }

        stage('Migrate Database') {
            steps {
                sh '''
                    cd messaging_app
                    docker-compose exec -T web python3 manage.py migrate --noinput
                '''
            }
        }

        stage('Run Tests') {
            steps {
                sh '''
                    cd messaging_app
                    docker compose exec -T web pytest --junitxml=report.xml
                '''
            }
            post {
                always {
                    junit 'messaging_app/report.xml'
                }
            }
        }
    }

    post {
        always {
            sh '''
                cd messaging_app
                docker-compose down
            '''
        }
    }
}
