pipeline {
    agent any

    stages {
        stage('Checkout Code') {
            steps {
                // No credentials needed for public repo
                git branch: 'master',
                    url: 'https://github.com/ylb43u/alx-backend-python.git'
            }
        }

        stage('Install Dependencies') {
            steps {
                sh '''
                    cd messaging_app
                    python3 -m venv venv
                    . venv/bin/activate
                    pip install --upgrade pip
                    pip install -r requirements.txt
                '''
            }
        }

        stage('Run Tests') {
            steps {
                sh '''
                    cd messaging_app
                    . venv/bin/activate
                    pytest --junitxml=report.xml
                '''
            }
            post {
                always {
                    junit 'messaging_app/report.xml'  // Publish test results
                }
            }
        }

        stage('Build Application') {
            steps {
                sh '''
                    cd messaging_app
                    . venv/bin/activate
                    docker build -t messaging-app .
                    docker run -d -p 5000:5000 --name messaging-app messaging-app
                    echo "Application is running on http://localhost:5000"
                '''
            }
        }
    }
}
